require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10

Rails/FilePath:
  EnforcedStyle: arguments

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false
